---

- name: Create user for jannovar-rest-api
  user:
    name: jannovar-rest-api
    home: /srv/jannovar-rest-api
    group: "{{ jannovar_server_nogroup_name }}"

- name: Create folder hierarchy
  file:
    state: directory
    dest: /srv/jannovar-rest-api/{{ jannovar_version }}
    owner: jannovar-rest-api
    group: "{{ jannovar_server_nogroup_name }}"
    mode: ug=rwX,o=
  loop:
    - /srv
    - /srv/jannovar-rest-api
    - /srv/jannovar-rest-api/{{ jannovar_version }}

- name: Download jannovar-cli JAR file
  get_url:
    url: https://search.maven.org/remotecontent?filepath=de/charite/compbio/jannovar-cli/{{ jannovar_version }}/jannovar-cli-{{ jannovar_version }}.jar
    dest: /srv/jannovar-rest-api/{{ jannovar_version }}/jannovar-cli-{{ jannovar_version }}.jar
  notify:
    - restart jannovar-rest-api

- name: Download and build databases (#1 may fail)
  become: true
  become_user: jannovar-rest-api
  shell: |
    cd /srv/jannovar-rest-api/{{ jannovar_version }}
    java -jar jannovar-cli-{{ jannovar_version }}.jar download -d {{ item }}
  args:
    creates: /srv/jannovar-rest-api/{{ jannovar_version }}/data/{{ item|regex_replace("/", "_") }}.ser
  failed_when: false
  loop: "{{ jannovar_server_databases }}"
  notify:
    - restart jannovar-rest-api

- name: Remove bogus chrM entry.
  shell: |
    set -euo pipefail
    export TMPDIR=$(mktemp -d)
    trap "rm -rf $TMPDIR" EXIT
    gzip -c -d /srv/jannovar-rest-api/{{ jannovar_version }}/data/{{ item }}/chromInfo.txt.gz >$TMPDIR/chromInfo.txt
    sed -i -e '/chrM.*16571/d' $TMPDIR/chromInfo.txt
    gzip -c $TMPDIR/chromInfo.txt >/srv/jannovar-rest-api/{{ jannovar_version }}/data/{{ item }}/chromInfo.txt.gz
  args:
    executable: /usr/bin/bash
  changed_when: false
  loop: "{{ jannovar_server_databases }}"

- name: Download and build databases (#2 must not fail)
  become: true
  become_user: jannovar-rest-api
  shell: |
    cd /srv/jannovar-rest-api/{{ jannovar_version }}
    java -jar jannovar-cli-{{ jannovar_version }}.jar download -d {{ item }}
  args:
    creates: /srv/jannovar-rest-api/{{ jannovar_version }}/data/{{ item|regex_replace("/", "_") }}.ser
  loop: "{{ jannovar_server_databases }}"
  notify:
    - restart jannovar-rest-api

- name: Install jannovar-rest-api systemd unit file
  template:
    src: jannovar-rest-api.service.j2
    dest: /etc/systemd/system/jannovar-rest-api.service
  notify:
    - daemon-reload
    - restart jannovar-rest-api

- name: flush handlers
  meta: flush_handlers

- name: Start jannovar-rest-api-* systemd unit
  systemd:
    state: started
    name: jannovar-rest-api
    enabled: true
